; Crystal Bowie Windows installer (Inno Setup 6 / ISPP).
;
; Product identity (name, version, publisher, output name, bundle ID) is NOT hardcoded here — it's
; #included from build\Installer\ProductInfo.iss, generated by CMake's configure_file() from the
; PRODUCT_NAME/COMPANY_NAME/BUNDLE_ID variables and PROJECT_VERSION in the repo root's CMakeLists.txt.
; Run `cmake -B build` at the repo root at least once before compiling this script (Installer\Windows\
; build_installer.ps1 does this check for you).
;
; Reusing this file for a future sibling project: nothing below should need editing except the AppId
; GUID (generate a fresh one, e.g. PowerShell `[guid]::NewGuid()`) and, if the plugin's format set
; changes, the [Components]/[Files] sections. Crystal Bowie's VST3 is a JUCE folder bundle (Contents\...
; inside), unlike the other Icebreaker Audio plugins' single-file VST3 — that's why its [Files] entry
; below uses a wildcard + recursesubdirs while CLAP (a single file) doesn't.
#include "..\..\build\Installer\ProductInfo.iss"

[Setup]
AppId={{635F4583-813B-4D35-B9BB-7EEE878662E2}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL=https://icebreakeraudio.com
DefaultDirName={commoncf}\{#MyAppPublisher}\{#MyAppName}
DisableDirPage=yes
DisableProgramGroupPage=yes
LicenseFile=License.txt
SetupIconFile=icon.ico
Compression=lzma2/max
SolidCompression=yes
WizardStyle=modern
OutputDir=Output
OutputBaseFilename={#MyAppName}-{#MyAppVersion}-Setup
ArchitecturesAllowed=x64
ArchitecturesInstallIn64BitMode=x64
Uninstallable=yes

; No Windows code-signing certificate exists yet. Once one does, uncomment and point these at it
; (see https://jrsoftware.org/ishelp/index.php?topic=setup_signtool for SignTool profile setup):
;SignTool=signtool
;SignedUninstaller=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Types]
Name: "full"; Description: "Full installation"
Name: "custom"; Description: "Custom installation"; Flags: iscustom

[Components]
Name: "clap"; Description: "CLAP Plugin"; Types: full custom
Name: "vst3"; Description: "VST3 Plugin"; Types: full custom

[Files]
Source: "..\..\build\CrystalBowie_artefacts\Release\CLAP\{#MyOutputName}.clap"; DestDir: "{commoncf}\CLAP"; Components: clap; Flags: ignoreversion
Source: "..\..\build\CrystalBowie_artefacts\Release\VST3\{#MyOutputName}.vst3\*"; DestDir: "{commoncf}\VST3\{#MyOutputName}.vst3"; Components: vst3; Flags: ignoreversion recursesubdirs
